import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';

const elements=new Map();
const listeners=new Map();
let savedState="";
const document={querySelector(key){if(!elements.has(key))elements.set(key,{innerHTML:'',textContent:'',value:'',addEventListener(){},classList:{add(){},remove(){}}});return elements.get(key)},addEventListener(type,handler){if(!listeners.has(type))listeners.set(type,[]);listeners.get(type).push(handler)},querySelectorAll(){return []}};
const sandbox={document,window:{addEventListener(){}},location:{hash:''},localStorage:{getItem(){return null},setItem(key,value){savedState=value}},structuredClone,console,setTimeout,clearTimeout,URL,Blob};
vm.createContext(sandbox);
vm.runInContext(readFileSync(new URL('./dist/app.js',import.meta.url),'utf8'),sandbox);
vm.runInContext(readFileSync(new URL('./dist/connections.js',import.meta.url),'utf8'),sandbox);
vm.runInContext(readFileSync(new URL('./dist/wizard.js',import.meta.url),'utf8'),sandbox);
const run=code=>vm.runInContext(code,sandbox);
assert.equal(run('wizardSteps.length'),3);
const emitInput=(id,value)=>{for(const listener of listeners.get('input')||[])listener({target:{id,value}})};
const originalRole=run('state.config.role');
run('page="settings";render()');
const settingsHTML=elements.get('#main').innerHTML;
for(const id of ['rules-bot-name','rules-welcome','rules-ai-prompt','live-api-key','manual-model','ai-enabled']){
  assert.equal(settingsHTML.split(`id="${id}"`).length-1,1,`Step 2 must expose exactly one ${id}`);
}
emitInput('rules-ai-prompt','測試角色：回答使用繁體中文。');
assert.equal(JSON.parse(savedState).config.role,'測試角色：回答使用繁體中文。');
assert.equal(run('configRows().find(r=>r[0]==="AI_ROLE")[1]'),'測試角色：回答使用繁體中文。');
emitInput('live-api-key','test-only-secret-never-export');
emitInput('manual-model','test-model');
assert.equal(run('runtime.keys[selectedProvider]'),'test-only-secret-never-export');
assert.equal(JSON.parse(savedState).config.model,'test-model');
assert.equal(JSON.parse(savedState).config.provider,run('selectedProvider'));
assert.ok(!savedState.includes('test-only-secret-never-export'));
assert.ok(!run('JSON.stringify(configRows())').includes('test-only-secret-never-export'));
assert.ok(!run('generateGas()').includes('test-only-secret-never-export'));
emitInput('rules-ai-prompt',originalRole);
run('runtime.keys={};state.config.model=""');
console.log('PASS: step 2 fields, Prompt persistence/export, model selection, API Key excluded from storage and exports.');

for(const [index,key] of ['sheets','settings','gas'].entries()){
  run(`page=${JSON.stringify(key)};render()`);
  assert.ok(elements.get('#main').innerHTML.includes(`步驟 ${index+1}：`));
  if(index<2)assert.ok(elements.get('#main').innerHTML.includes('下一步：'));
}
run('page="test";render()');
assert.equal(run('wizardIndex()'),2);
assert.ok(elements.get('#main').innerHTML.includes('id="chat-form"'));
assert.equal(run('parseCSV(\'A,B\\r\\n"x,y","z"\\r\\n"multi\\nline","say ""yes"""\').length'),3);
assert.equal(run('parseCSV(\'A,B\\n"x,y",z\')[1][0]'),'x,y');
assert.throws(()=>run('parseCSV(\'A\\n"broken\')'),/引號/);
assert.ok(run('validateHeaders(["A","A"])'));
assert.ok(run('validateHeaders(["A",""])'));
assert.equal(run('validateHeaders(["A","B"])'),'');
assert.equal(run('validGoogleUrl("https://docs.google.com.evil.test/spreadsheets/d/abc", "sheet")'),false);
assert.equal(run('validGoogleUrl("https://docs.google.com/spreadsheets/d/abc", "sheet")'),true);
assert.equal(run('retrieve("第 8 頁表格").some(x=>x.doc==="d3")'),false,'Pending OCR must not enter retrieval');
assert.equal(run('retrieve("zzzzunfindable").length'),0);
assert.equal(run('triggerMatch("課程退費")'),true);
assert.equal(run('triggerMatch("哈囉")'),false);
assert.ok(run('retrieve("退費規定").some(x=>x.text.includes("全額退費"))'));
assert.equal(run('state.config.ragEnabled'),false);
assert.equal(run('state.config.aiEnabled'),false);
assert.equal(run('matchRule("你好").type'),'text');
assert.ok(run('ask("你好").text.includes("歡迎")'));
assert.equal(run('ask("完全不相干的查詢").mode'),'fallback');
assert.equal(run('ruleError([{keyword:"link",text:"text",type:"url",url:"javascript:bad"}])'),'請輸入有效的 http 或 https 網址。');
assert.equal(run('ruleReply({text:"報名連結",type:"url",url:"https://example.com"})'),'報名連結\nhttps://example.com');
const code=run('generateGas()');
new vm.Script(code);
const properties=new Map([['SPREADSHEET_ID','test-id'],['CONFIG_SHEET_ID','42']]);
const fixture=[['AI_Response','message','userid','Time'],['AI 入門','C001','user-example','2026-09-24']];
const gasSandbox={PropertiesService:{getScriptProperties:()=>({getProperty:k=>properties.get(k),setProperty:(k,v)=>properties.set(k,v)})},SpreadsheetApp:{openById:()=>({getSheetByName:()=>({getDataRange:()=>({getDisplayValues:()=>structuredClone(fixture)})}),getSheets:()=>[{getSheetId:()=>42,getDataRange:()=>({getDisplayValues:()=>[['設定鍵','設定值'],['BOT_NAME','測試助教']]})}]})}};
vm.createContext(gasSandbox);vm.runInContext(code,gasSandbox);
const result=vm.runInContext('queryRecords_("C001")',gasSandbox);
assert.equal(result[0]['AI_Response'],'AI 入門','Generated GAS must map reordered columns by header');
assert.equal(vm.runInContext('testSheetConnection().botName',gasSandbox),'測試助教');
assert.equal(vm.runInContext('shouldTrigger_("報名課程",{TRIGGER_KEYWORDS:"[\\"課程\\"]",TRIGGER_MODE:"exact"})',gasSandbox),false);
fixture[0][0]='其他欄位';
assert.throws(()=>vm.runInContext('readRecords_()',gasSandbox),/缺少欄位/);
const ruleRows=[['規則ID','啟用','關鍵詞','比對方式','回覆類型','顯示文字','網址'],['r1','TRUE','報名','exact','url','點此報名','https://example.com/apply'],['r2','FALSE','停用','contains','text','不應回覆','']];
const ruleConfig=[['設定鍵','設定值'],['AI_ENABLED','false'],['RAG_ENABLED','false'],['NO_ANSWER_MESSAGE','沒有符合規則']];
const rulesGas={PropertiesService:gasSandbox.PropertiesService,SpreadsheetApp:{openById:()=>({getSheetByName:name=>name==='Keywords'?{getDataRange:()=>({getDisplayValues:()=>structuredClone(ruleRows)})}:null,getSheets:()=>[{getName:()=> 'Setting',getSheetId:()=>42,getDataRange:()=>({getDisplayValues:()=>structuredClone(ruleConfig)})},{getName:()=> 'Keywords',getDataRange:()=>({getDisplayValues:()=>structuredClone(ruleRows)})}]})},UrlFetchApp:{fetch(){throw Error('Basic bot must not call external services')}}};
vm.createContext(rulesGas);vm.runInContext(code,rulesGas);
assert.equal(vm.runInContext('handleTextMessage_("報名")',rulesGas),'點此報名\nhttps://example.com/apply');
assert.equal(vm.runInContext('handleTextMessage_("其他訊息")',rulesGas),'沒有符合規則');
assert.equal(vm.runInContext('handleTextMessage_("停用")',rulesGas),'沒有符合規則');
// A row added directly in Google Sheets must be picked up on the next message.
ruleRows.push(['r3','TRUE','營業時間','exact','text','週一至週五 09:00–18:00','']);
assert.equal(vm.runInContext('handleTextMessage_("營業時間")',rulesGas),'週一至週五 09:00–18:00');
ruleRows[3][5]='每日 10:00–17:00';
assert.equal(vm.runInContext('handleTextMessage_("營業時間")',rulesGas),'每日 10:00–17:00');
ruleRows[3][1]='FALSE';
assert.equal(vm.runInContext('handleTextMessage_("營業時間")',rulesGas),'沒有符合規則');
console.log('PASS: Google Sheet rule additions, edits and disabling are read on each message without regenerating GAS.');
console.log('PASS: CSV quoting, header validation, Google URL validation, OCR exclusion, missing-answer retrieval, triggers, GAS syntax, reordered columns, missing columns, settings lookup.');
